### ISSUE TITLE
All set commands do not work with Viessmann KW protocol

### ISSUE THREAD

**Issue by armintan** [steand/optolink#10] opened 2018-02-04 05:48 UTC
All set commands do not send the value to be set in ViessmannKW.java

**Comment by Hotte37** [comment] 2018-02-25 13:22
I have the same issues. I found this [commit](https://github.com/steand/optolink/pull/2/commits/8a43b1be724c6260e4c2bd41f0de4ea4a6b93624) that claims to solve the write problem but it is not merged into the main branch. 
I am waiting for the new release with this fix since a few month.

@steand 
Do you see a chance for building a new relase in the near future?

**Comment by mikeww1** [comment] 2018-02-28 14:34
I can confirm that the commit of @Sbried does actually fix the problem. I am using the version with his modifications and there is no USB timeout and I can write in KW mode to my heater.
If you know how to compile the stuff you could use the[ fork of Sbried](https://github.com/Sbried/optolink)  to get the changes. Of course it would be great if @steand could update his version.

**Comment by Hotte37** [comment] 2018-03-13 10:27
I tried to build the source with luna and oxigen. I allways have trouble with the maven dependencies. Eclipse was not able to find the external packages even if they are downloaded in a local folder and i can even see the reference to it in the project tree of eclipse:( 
I am new with Java and i read a lot of documentation the last two days ... but obviously not enough.
Now i decided to give up.

Was anybody able to build the current version (with the merged pull request #2) and can provide it to @steand to save it as the Release 1.0.1?

**Comment by Hotte37** [comment] 2018-03-13 23:00
I tried to build the jar without maven and this worked.

**Comment by lewie** [comment] 2018-03-14 07:33
I hope this helps:

compiled jars: https://github.com/lewie/optolink/tree/master_Sbried_jars
changes: https://github.com/steand/optolink/pull/13

**Comment by Hotte37** [comment] 2018-03-14 13:35
Yes it helped. I commended out the "runtime" scope and now it compiles with maven without any problems.
I now read the documentation of maven dependency scope and now it is clear to me.
But without your help, i never would have found this solution.

**Comment by steand** [comment] 2018-03-18 10:49
I have merged: #13

**Closed as completed by steand** 2018-03-18 10:49 UTC

**Comment by sVnsation** [comment] 2018-09-27 15:39
I tested the compiled jars of @lewie. The changes of @Sbried breaks the 'set function' for protocol 300.
